#!/bin/tcsh

setenv JobName JOBNAMETEMPLATE

echo  "Job started at "
\date;

setenv CMSSW_VER 4_1_2
setenv CMSSW_DIR ${CMSSW_BASE}/src/ZZAnalysis/Examples/test 
setenv LXBATCH_DIR `pwd`

cd $CMSSW_DIR
eval `scramv1 runtime -csh`
cd $LXBATCH_DIR

cp  ${CMSSW_DIR}/submittedCfg/${JobName}_cfg.py .
echo "cmsRun ${JobName}_cfg.py"

cmsRun ${JobName}_cfg.py >& ${JobName}.out;

echo "Content of working directory is: "
\ls -lrt

rfcp OUTFILETEMPLATE  $CASTOR_HOME/Zbb2010Ntuples/v3
rfcp ${JobName}.out   ${CASTOR_HOME}/test/

echo  "Job ended at "
\date;

exit 0
